### ISSUE TITLE
Gauge API failed to start - Connection issue: GAUGE_INTERNAL_PORT

### ISSUE THREAD

**Issue by asarkisian** [kashishm/gauge-python#14]
### Description
Add the expected behavior/issue description/Actual behavior here
My gauge installation stopped working. It is throwing the following error message:
Traceback (most recent call last):
  File "start.py", line 25, in <module>
    main()
  File "start.py", line 17, in main
    s = connection.connect()
  File "/usr/local/lib/python3.5/site-packages/getgauge/connection.py", line 10, in connect
    s.connect(('localhost', int(os.environ['GAUGE_INTERNAL_PORT'])))
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
Failed to start gauge API: Runner with pid 20637 quit unexpectedly(exit status 1).

### Steps to reproduce
1. Install gauge on MAC OSX Sierra 10.12.6 via the terminal using:
  a. brew update
  b. brew install gauge
  c. gauge install python
2. Ensure you have python3 installed and run the following:
  a. pip3 install getgauge
  b. pip3 list   <-- verify if it got installed
3. Create an empty folder in your home folder
  a. mkdir temp
  b. cd temp
4. Initialize the project
  a. gauge init python
5. Update env/default/python.properties to use python3 instead
6. Execute the dummy test case that comes with gauge:
  a. gauge run specs
7. Verify the error message you get. Verify if you see any error message pertaining to GAUGE_INTERNAL_PORT and that the Gauge API failed to start.

### Information that will help us debug

* Gauge version

* Gauge Python plugin version: getgauge (0.2.2)
* Python version: 3.5.2
* PIP3 version: pip 9.0.1 from /usr/local/lib/python3.5/site-packages (python 3.5)
* `getgauge` package version, run `pip3 show getgauge` to get it
Name: getgauge
Version: 0.2.2
Summary: Enables Python support for Gauge
Home-page: https://github.com/kashishm/gauge-python
Author: Kashish Munjal
Author-email: kashishmunjal64@gmail.com
License: MIT
Location: /usr/local/lib/python3.5/site-packages
Requires: protobuf, redBaron, colorama

* OS information
MAC OSX 10.12.6 Sierra using both the built-in terminal and iTerm2 3.1.2

**Comment by asarkisian** [comment]
<img width="206" alt="screen shot 2017-10-05 at 12 13 20 pm" src="https://user-images.githubusercontent.com/19278388/31248060-67d8ed22-a9c7-11e7-85b3-1f24fd3de7a0.png">
<img width="830" alt="screen shot 2017-10-05 at 12 13 35 pm" src="https://user-images.githubusercontent.com/19278388/31248059-67d85722-a9c7-11e7-9add-0bb03934fc69.png">
<img width="256" alt="screen shot 2017-10-05 at 12 13 56 pm" src="https://user-images.githubusercontent.com/19278388/31248061-67d92f4e-a9c7-11e7-9b9d-8ce44a8761be.png">

**Comment by asarkisian** [comment]
NOTE: This works when I initialize with Java. This is strictly isolated to Python3.

Python (v2) also does not work.

**Comment by asarkisian** [comment]
Uninstalled python3.5 and installed python3.6 and still same issue.

**Comment by asarkisian** [comment]
Issue resolved.

Steps:
1. vim /etc/hosts
2. Add the following:
127.0.0.1 localhost

3. Exit vim
4. Try again and it should work
