### ISSUE TITLE
problem when running the sample

### ISSUE THREAD

**Issue by stumpyfr** [kashishm/gauge-python#4]
I installed gauge-python with `gauge --install python`, made the init `gauge --init python` then tried to run it with `gauge specs/example.spec` but the result is not really what I expected :).
Did I missed something?

```
gauge specs/example.spec
# Specification Heading
  ## Vowel counts in single word	Traceback (most recent call last):
  File "./start.py", line 18, in <module>
    main()
  File "./start.py", line 14, in main
    processor.dispatch_messages(s)
  File "/usr/local/lib/python2.7/site-packages/getgauge/processor.py", line 142, in dispatch_messages
    processors[request.messageType](request, response, socket)
  File "/usr/local/lib/python2.7/site-packages/getgauge/processor.py", line 75, in _execute_before_scenario_hook
    run_hook(request, response, registry.before_scenario(tags), execution_info)
  File "/usr/local/lib/python2.7/site-packages/getgauge/executor.py", line 24, in run_hook
    if len(inspect.signature(hook).parameters) == 0:
AttributeError: 'module' object has no attribute 'signature'
    Error Message: Connection closed [127.0.0.1:63970] cause: EOF
    Stacktrace:

    Error Message: write tcp 127.0.0.1:63969->127.0.0.1:63970: use of closed network connection
    Stacktrace:


  Failed to initialize scenario datastore. Error: write tcp 127.0.0.1:63969->127.0.0.1:63970: use of closed network connection
  write tcp 127.0.0.1:63969->127.0.0.1:63970: use of closed network connection
  Error Message: write tcp 127.0.0.1:63969->127.0.0.1:63970: use of closed network connection
  Stacktrace:


  Error Message: write tcp 127.0.0.1:63969->127.0.0.1:63970: use of closed network connection
  Stacktrace:

Unable to connect to plugin Html Report 2.1.0. proto: required field "SuiteExecutionResult.SuiteResult.SpecResults.ProtoSpec.PreHookFailure.StackTrace" not set

Specifications:	1 executed	0 passed	1 failed	0 skipped
Scenarios:	1 executed	1 passed	0 failed	1 skipped

Total time taken: 233ms
```

* Mac 10.11.3
* python 2.7.11
* gauge 0.4.0
* gauge-python 0.1.2

**Comment by kashishm** [comment]
You have installed `getgauge 0.1.2` which only supports python3, for Python 2, use `pip install "getgauge<0.1.0"`

**Comment by stumpyfr** [comment]
Just made the switch to python 3 and solved the problem.
My mistake, sorry.
